### ISSUE TITLE
Missing devDependency

### ISSUE THREAD

**Issue by renancarvalho** [chiefGui/reswitch#2]
It fails when you run `npm run test`. I realized that `npm install` didn't install mocha because it is not specified as a dev dependency.

**Comment by renancarvalho** [comment]
@chiefGui check this PR

https://github.com/chiefGui/reswitch/pull/3

Cheers!

**Comment by chiefGui** [comment]
Your PR arrived on https://github.com/chiefGui/reswitch/tree/v0.1.2.
